alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias dmesg='dmesg --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CFlh'
alias diskspace='du -Sh | sort -n -r | more'
alias orphans='[[ -n $(pacman -Qdt) ]] && sudo pacman -Rs $(pacman -Qdtq) || echo "No orphans to remove"'
